CREATE TABLE IF NOT EXISTS "User_password"{
	"id" UUID NOT NULL,
	"password" VARCHAR (128) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	CONSTRAINT "fk_id" FOREIGN KEY ("id") REFERENCES "Person" ("id") ON DELETE CASCADE ON UPDATE CASCADE
} WITHOUD OIDS;