version: "3"
services:
  postgres:
    image: postgres:14-alpine
    restart: on-failure
    volumes:
        - ./data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=userland
        - PGPORT=5432
    networks: 
      default:
        aliases: 
          - db_userland
    expose:
      - 5432
  adminer:
    image: adminer:standalone
    restart: on-failure
    ports:
      - "8081:8080/tcp"
    networks:
      default:
        aliases:
          - adminer
  userland:
    image: golang:1.16
    working_dir: /todolist
    volumes:
      - ./:/todolist:ro
    command: /bin/bash -c "go run ."
    ports:
      - "8080:80/tcp"
    networks:
      default:
        aliases:
          - userland_service
  redis:
    image: redis:6.2.6-alpine
    restart: on-failure
    expose: 
      - 6379
    ports:
      - "6379:6379/tcp"
networks: 
  default:



